# Environment Setup

Installing PyTorch, OpenCV, the COCO API, and clone the official YOLOv5
repository. YOLOv5 already implements CIoU loss, mosaic/HSV/flip augmentation, and cosine LR scheduling internally configures.

In [2]:
# --- Install core libraries and COCO API
!pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 2>/dev/null || pip install -q torch torchvision torchaudio
!pip install -q opencv-python-headless pandas pyyaml tqdm matplotlib seaborn Pillow requests
!pip install -q pycocotools
!pip install -q onnx onnxruntime
!pip install -q tabulate

# Clone YOLOv5
import os

if not os.path.isdir("yolov5"):
    !git clone -q https://github.com/ultralytics/yolov5.git

%cd yolov5
!pip install -q -r requirements.txt
%cd ..

import torch
print("Torch version   :", torch.__version__)
print("CUDA available   :", torch.cuda.is_available())
print("Device            :", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 83.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 MB 84.4 MB/s eta 0:00:00
/content/yolov5
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 53.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.1/131.1 kB 13.6 MB/s eta 0:00:00
/content
Torch version   : 2.11.0+cu128
CUDA available   : True
Device            : Tesla T4

In [3]:
import torch

if not torch.cuda.is_available():
    raise RuntimeError(
        "No GPU detected! Training YOLOv5 variants on CPU is extremely slow "
        "(potentially many hours per variant) and is not recommended for this notebook.\n"
        "In Colab: Runtime -> Change runtime type -> Hardware accelerator -> GPU (T4 is fine), "
        "then Runtime -> Restart session, and re-run this notebook from the top."
    )

print(f"GPU detected: {torch.cuda.get_device_name(0)} -- safe to proceed with training.")

GPU detected: Tesla T4 -- safe to proceed with training.

## 1. Data Preprocessing
### Requirement 1: Download and preprocess COCO (resizing + annotation parsing), split 80/10/10
### Tool: COCO API (`pycocotools`)

In [4]:
# 1.1 Download COCO 2017 annotation files (small, ~241MB)
import os

ANNOT_DIR = "coco_annotations"
os.makedirs(ANNOT_DIR, exist_ok=True)

ANNOT_ZIP_URL = "http://images.cocodataset.org/annotations/annotations_trainval2017.zip"
zip_path = os.path.join(ANNOT_DIR, "annotations_trainval2017.zip")

if not os.path.exists(zip_path):
    !wget -q -O {zip_path} {ANNOT_ZIP_URL}
!unzip -q -o {zip_path} -d {ANNOT_DIR}

print("Annotation files:", os.listdir(os.path.join(ANNOT_DIR, "annotations")))

Annotation files: ['captions_val2017.json', 'instances_train2017.json', 'instances_val2017.json', 'captions_train2017.json', 'person_keypoints_train2017.json', 'person_keypoints_val2017.json']

In [5]:
# 1.2 Load annotations with the official COCO API (pycocotools)
from pycocotools.coco import COCO

train_ann_path = os.path.join(ANNOT_DIR, "annotations", "instances_train2017.json")
val_ann_path   = os.path.join(ANNOT_DIR, "annotations", "instances_val2017.json")

coco_train = COCO(train_ann_path)
coco_val   = COCO(val_ann_path)

categories = coco_train.loadCats(coco_train.getCatIds())      # COCO API call
categories = sorted(categories, key=lambda c: c["id"])
COCO_CLASSES   = [c["name"] for c in categories]
COCO_ID_TO_YOLO_ID = {c["id"]: i for i, c in enumerate(categories)}

print(f"Loaded {len(COCO_CLASSES)} COCO categories via the COCO API.")
print(COCO_CLASSES[:10], "...")

loading annotations into memory...
Done (t=18.64s)
creating index...
index created!
loading annotations into memory...
Done (t=0.51s)
creating index...
index created!
Loaded 80 COCO categories via the COCO API.
['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light'] ...

In [6]:
# 1.3 Stratified sampling: pull a fixed number of images PER CATEGORY (not pure random)
import random
from collections import Counter

random.seed(42)
# images per category; 50 x 80 categories = up to ~4,000 images
IMAGES_PER_CATEGORY = 50

selected = {}  # key: (split_name, img_id)  -> value: coco_api handle (coco_train or coco_val)

for cat in categories:   # loop over all 80 categories; each getImgIds() call is fast (metadata only, no downloads)
    cat_id = cat["id"]

    # training-
    train_ids_for_cat = coco_train.getImgIds(catIds=[cat_id])   # COCO API: images containing this category
    random.shuffle(train_ids_for_cat)

    added = 0
    for img_id in train_ids_for_cat:
        key = ("train2017", img_id)
        if key not in selected:
            selected[key] = coco_train
            added += 1
        if added >= IMAGES_PER_CATEGORY:
            break

    # if train2017 didn't have enough images for this (rare) category, top up from val2017
    if added < IMAGES_PER_CATEGORY:
        val_ids_for_cat = coco_val.getImgIds(catIds=[cat_id])   # COCO API: images containing this category
        random.shuffle(val_ids_for_cat)
        for img_id in val_ids_for_cat:
            key = ("val2017", img_id)
            if key not in selected:
                selected[key] = coco_val
                added += 1
            if added >= IMAGES_PER_CATEGORY:
                break

sampled_ids = [(split, img_id, api) for (split, img_id), api in selected.items()]

print(f"Target: up to {IMAGES_PER_CATEGORY} images/category x {len(categories)} categories "
      f"= {IMAGES_PER_CATEGORY * len(categories)} max.")
print(f"Actual unique images selected: {len(sampled_ids)} "
      f"(lower than the max is expected/fine -- many images contain MULTIPLE categories at once, "
      f"so the same image can count towards several categories' quotas simultaneously).")

Target: up to 50 images/category x 80 categories = 4000 max.
Actual unique images selected: 4000 (lower than the max is expected/fine -- many images contain MULTIPLE categories at once, so the same image can count towards several categories' quotas simultaneously).

In [7]:
# 1.3b Verify category coverage BEFORE downloading anything
import pandas as pd

category_coverage = Counter()
for split_name, img_id, api in sampled_ids:
    ann_ids = api.getAnnIds(imgIds=img_id)
    anns = api.loadAnns(ann_ids)
    cats_in_image = set(a["category_id"] for a in anns)
    for c in cats_in_image:
        category_coverage[c] += 1

coverage_rows = [
    {"category": cat["name"], "images_containing_it": category_coverage.get(cat["id"], 0)}
    for cat in categories
]
coverage_df = pd.DataFrame(coverage_rows).sort_values("images_containing_it").reset_index(drop=True)

n_zero_coverage = (coverage_df["images_containing_it"] == 0).sum()
print(f"Categories with ZERO coverage in our sample: {n_zero_coverage} / {len(categories)}")
print("\nLowest-coverage categories (worth checking):")
print(coverage_df.head(10).to_string(index=False))
print("\nHighest-coverage categories:")
print(coverage_df.tail(5).to_string(index=False))

Categories with ZERO coverage in our sample: 0 / 80

Lowest-coverage categories (worth checking):
     category  images_containing_it
   hair drier                    53
         bear                    54
        zebra                    54
     elephant                    58
        sheep                    59
      giraffe                    61
      toaster                    62
    snowboard                    63
     airplane                    64
parking meter                    65

Highest-coverage categories:
    category  images_containing_it
      bottle                   492
         cup                   573
       chair                   645
dining table                   652
      person                  2110

In [8]:
# 1.4 Download the sampled images from the official COCO image server
import requests
from tqdm import tqdm

RAW_IMG_DIR = "coco_images_raw"
os.makedirs(RAW_IMG_DIR, exist_ok=True)

downloaded = []  # (local_image_path, coco_api_handle, image_id)

for split_name, img_id, coco_api in tqdm(sampled_ids, desc="Downloading COCO images"):
    img_info = coco_api.loadImgs(img_id)[0]      # COCO API: fetch image metadata (incl. URL)
    file_name = f"{split_name}_{img_info['file_name']}"
    out_path = os.path.join(RAW_IMG_DIR, file_name)

    if not os.path.exists(out_path):
        try:
            resp = requests.get(img_info["coco_url"], timeout=10)
            if resp.status_code == 200:
                with open(out_path, "wb") as f:
                    f.write(resp.content)
        except requests.RequestException:
            continue

    if os.path.exists(out_path):
        downloaded.append((out_path, coco_api, img_id))

print(f"Successfully downloaded {len(downloaded)} / {len(sampled_ids)} images.")

Downloading COCO images: 100%|██████████| 4000/4000 [1:24:54<00:00,  1.27s/it]

Successfully downloaded 4000 / 4000 images.

In [9]:
# 1.5 Parse annotations (via COCO API) + resize images + write YOLO-format labels
import cv2
import numpy as np

IMG_SIZE = 640
STAGE_DIR = "coco_yolo_staging"
os.makedirs(os.path.join(STAGE_DIR, "images"), exist_ok=True)
os.makedirs(os.path.join(STAGE_DIR, "labels"), exist_ok=True)

def letterbox_resize(image, size=IMG_SIZE):
    """Resize keeping aspect ratio, pad the rest (standard YOLO preprocessing)."""
    h, w = image.shape[:2]
    scale = size / max(h, w)
    nh, nw = int(h * scale), int(w * scale)
    resized = cv2.resize(image, (nw, nh))
    canvas = 128 * np.ones((size, size, 3), dtype=np.uint8)
    top, left = (size - nh) // 2, (size - nw) // 2
    canvas[top:top + nh, left:left + nw] = resized
    return canvas, scale, top, left

staged_stems = []
next_numeric_id = 1

for img_path, coco_api, img_id in tqdm(downloaded, desc="Preprocessing"):
    image = cv2.imread(img_path)
    if image is None:
        continue
    orig_h, orig_w = image.shape[:2]

    # annotation parsing via the COCO API
    ann_ids = coco_api.getAnnIds(imgIds=img_id, iscrowd=False)
    anns = coco_api.loadAnns(ann_ids)
    if not anns:
        continue

    resized, scale, pad_top, pad_left = letterbox_resize(image, IMG_SIZE)

    stem = f"{next_numeric_id:012d}"
    next_numeric_id += 1

    out_img_path = os.path.join(STAGE_DIR, "images", stem + ".jpg")
    cv2.imwrite(out_img_path, resized)

    out_lines = []
    for ann in anns:
        yolo_class_id = COCO_ID_TO_YOLO_ID[ann["category_id"]]
        x, y, box_w, box_h = ann["bbox"]

        # Map box coordinates through the same resize + padding applied to the image
        xmin_r = x * scale + pad_left
        ymin_r = y * scale + pad_top
        xmax_r = (x + box_w) * scale + pad_left
        ymax_r = (y + box_h) * scale + pad_top

        xc = ((xmin_r + xmax_r) / 2.0) / IMG_SIZE
        yc = ((ymin_r + ymax_r) / 2.0) / IMG_SIZE
        w_n = (xmax_r - xmin_r) / IMG_SIZE
        h_n = (ymax_r - ymin_r) / IMG_SIZE

        out_lines.append(f"{yolo_class_id} {xc:.6f} {yc:.6f} {w_n:.6f} {h_n:.6f}")

    out_lbl_path = os.path.join(STAGE_DIR, "labels", stem + ".txt")
    with open(out_lbl_path, "w") as f:
        f.write("\n".join(out_lines))

    staged_stems.append(stem)

print(f"Preprocessed {len(staged_stems)} image/label pairs into '{STAGE_DIR}'.")
print(f"Example filenames: {staged_stems[:3]} ... (purely numeric, matches val.py's id parsing)")

Preprocessing: 100%|██████████| 4000/4000 [00:26<00:00, 150.03it/s]

Preprocessed 4000 image/label pairs into 'coco_yolo_staging'.
Example filenames: ['000000000001', '000000000002', '000000000003'] ... (purely numeric, matches val.py's id parsing)

In [10]:
# 1.6 Split the combined pool ourselves into train / val / test = 80% / 10% / 10%
random.seed(42)
random.shuffle(staged_stems)

n_total = len(staged_stems)
n_train = int(0.80 * n_total)
n_val   = int(0.10 * n_total)
# remainder -> test (keeps the split exact even with integer rounding)

train_stems = staged_stems[:n_train]
val_stems   = staged_stems[n_train:n_train + n_val]
test_stems  = staged_stems[n_train + n_val:]

print(f"Train: {len(train_stems)}  ({len(train_stems)/n_total:.1%})")
print(f"Val  : {len(val_stems)}  ({len(val_stems)/n_total:.1%})")
print(f"Test : {len(test_stems)}  ({len(test_stems)/n_total:.1%})")

Train: 3200  (80.0%)
Val  : 400  (10.0%)
Test : 400  (10.0%)

In [11]:
# 1.7 Materialize the split into the folder layout YOLOv5 expects
import shutil

FINAL_DIR = "coco_yolo_dataset"

def build_split(split_name, stems):
    img_out = os.path.join(FINAL_DIR, "images", split_name)
    lbl_out = os.path.join(FINAL_DIR, "labels", split_name)
    os.makedirs(img_out, exist_ok=True)
    os.makedirs(lbl_out, exist_ok=True)
    for stem in stems:
        shutil.copy(os.path.join(STAGE_DIR, "images", stem + ".jpg"), os.path.join(img_out, stem + ".jpg"))
        shutil.copy(os.path.join(STAGE_DIR, "labels", stem + ".txt"), os.path.join(lbl_out, stem + ".txt"))

for split_name, stems in [("train", train_stems), ("val", val_stems), ("test", test_stems)]:
    build_split(split_name, stems)

print("Final YOLOv5 dataset directory structure:")
!find {FINAL_DIR} -maxdepth 2 -type d

Final YOLOv5 dataset directory structure:
coco_yolo_dataset
coco_yolo_dataset/labels
coco_yolo_dataset/labels/test
coco_yolo_dataset/labels/val
coco_yolo_dataset/labels/train
coco_yolo_dataset/images
coco_yolo_dataset/images/test
coco_yolo_dataset/images/val
coco_yolo_dataset/images/train

In [12]:
# 1.8 Write the data.yaml config YOLOv5 needs (paths + class names)
import yaml

data_yaml = {
    "path": os.path.abspath(FINAL_DIR),
    "train": "images/train",
    "val": "images/val",
    "test": "images/test",
    "nc": len(COCO_CLASSES),
    "names": COCO_CLASSES,
}

with open("coco_subset.yaml", "w") as f:
    yaml.safe_dump(data_yaml, f, sort_keys=False)

print(open("coco_subset.yaml").read()[:400], "...")

path: /content/coco_yolo_dataset
train: images/train
val: images/val
test: images/test
nc: 80
names:
- person
- bicycle
- car
- motorcycle
- airplane
- bus
- train
- truck
- boat
- traffic light
- fire hydrant
- stop sign
- parking meter
- bench
- bird
- cat
- dog
- horse
- sheep
- cow
- elephant
- bear
- zebra
- giraffe
- backpack
- umbrella
- handbag
- tie
- suitcase
- frisbee
- skis
- snowboard ...

## 2. Model Architecture
### Requirement 2: YOLOv5 base model pre-trained on COCO, fine-tuned; compare s/m/l variants

In [13]:
# 2.1 Load each pre-trained (on COCO) variant via torch.hub and inspect
import torch

YOLO_VARIANTS = ["yolov5s", "yolov5m", "yolov5l"]

variant_params = {}
for variant in YOLO_VARIANTS:
    model = torch.hub.load("ultralytics/yolov5", variant, pretrained=True, verbose=False)
    n_params = sum(p.numel() for p in model.model.parameters())
    variant_params[variant] = n_params
    print(f"{variant:10s} -> {n_params/1e6:.2f}M parameters (pre-trained on full COCO)")
    del model

The repository ultralytics_yolov5 does not belong to the list of trusted repositories and as such cannot be downloaded. Do you trust this repository and wish to add it to the trusted list of repositories (y/N)?y
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.

YOLOv5 🚀 2026-7-21 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Downloading https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s.pt to yolov5s.pt...
100%|██████████| 14.1M/14.1M [00:00<00:00, 254MB/s]

Fusing layers...
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Adding AutoShape...

yolov5s    -> 7.23M parameters (pre-trained on full COCO)

YOLOv5 🚀 2026-7-21 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Downloading https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5m.pt to yolov5m.pt...
100%|██████████| 40.8M/40.8M [00:01<00:00, 40.2MB/s]

Fusing layers...
YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients, 48.9 GFLOPs
Adding AutoShape...
YOLOv5 🚀 2026-7-21 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Downloading https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5l.pt to yolov5l.pt...

yolov5m    -> 21.17M parameters (pre-trained on full COCO)

100%|██████████| 89.3M/89.3M [00:04<00:00, 22.5MB/s]

Fusing layers...
YOLOv5l summary: 367 layers, 46533693 parameters, 0 gradients, 109.0 GFLOPs
Adding AutoShape...

yolov5l    -> 46.53M parameters (pre-trained on full COCO)

## 3. Training and Evaluation
### Requirement 3: AdamW/SGD + CIoU loss; mAP / AP50 / AP75; augmentation + LR scheduling
### Also completes Requirement 2's "experiment with different variants"

In [14]:
# 3.1 Shared training configuration
EPOCHS    = 30
BATCH     = 16
IMG_SIZE  = 640
OPTIMIZER = "AdamW"

print(f"Training config -> epochs={EPOCHS}, batch={BATCH}, img_size={IMG_SIZE}, optimizer={OPTIMIZER}")
print(f"Variants to train: {YOLO_VARIANTS}")

Training config -> epochs=30, batch=16, img_size=640, optimizer=AdamW
Variants to train: ['yolov5s', 'yolov5m', 'yolov5l']

In [15]:
# --- 3.2 Fine-tune EACH variant (s, m, l) on our COCO subset ---

for variant in YOLO_VARIANTS:
    weights_out = f"runs_train/coco_{variant}_run/weights/best.pt"

    if os.path.exists(weights_out):
        print(f"\n===== Skipping {variant}: best.pt already exists at {weights_out} =====")
        continue

    print(f"\n===== Training {variant} =====")
    !python yolov5/train.py \
        --img {IMG_SIZE} \
        --batch {BATCH} \
        --epochs {EPOCHS} \
        --data coco_subset.yaml \
        --weights {variant}.pt \
        --optimizer {OPTIMIZER} \
        --cos-lr \
        --hyp yolov5/data/hyps/hyp.scratch-low.yaml \
        --name coco_{variant}_run \
        --project runs_train \
        --exist-ok

    # Verify training actually produced weights before moving to the next variant
    # if it didn't, stop here with a clear error rather than silently continuing to val.py later.
    if not os.path.exists(weights_out):
        raise RuntimeError(
            f"Training for {variant} did NOT produce {weights_out}. "
            f"Scroll up through this cell's output above to find the actual error "
            f"(e.g. CUDA out-of-memory, dataset path issue, or a Colab disconnect)."
        )

===== Training yolov5s =====
wandb: WARNING ⚠️ wandb is deprecated and will be removed in a future release. See supported integrations at https://github.com/ultralytics/yolov5#integrations.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: (30 second timeout)
wandb: WARNING W&B disabled due to login timeout.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
train: weights=yolov5s.pt, cfg=, data=coco_subset.yaml, hyp=yolov5/data/hyps/hyp.scratch-low.yaml, epochs=30, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, evolve_population=yolov5/data/hyps, resume_evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=AdamW, sync_bn=False, workers=8, project=runs_train, name=coco_yolov5s_run, exist_ok=True, quad=False, cos_lr=True, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest, ndjson_console=False, ndjson_file=False
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v7.0-519-g6be609f3 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Comet: run 'pip install comet_ml' to automatically track and visualize YOLOv5 🚀 runs in Comet
TensorBoard: Start with 'tensorboard --logdir runs_train', view at http://localhost:6006/
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.ttf to /root/.config/Ultralytics/Arial.ttf...
100% 755k/755k [00:00<00:00, 116MB/s]

                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     18816  models.common.C3                        [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  2    115712  models.common.C3                        [128, 128, 2]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  3    625152  models.common.C3                        [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 24      [17, 20, 23]  1    229245  models.yolo.Detect                      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model summary: 214 layers, 7235389 parameters, 7235389 gradients, 16.6 GFLOPs

Transferred 349/349 items from yolov5s.pt
AMP: checks passed ✅
optimizer: AdamW(lr=0.01) with parameter groups 57 weight(decay=0.0), 60 weight(decay=0.0005), 60 bias
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
train: Scanning /content/coco_yolo_dataset/labels/train... 3200 images, 0 backgrounds, 0 corrupt: 100% 3200/3200 [00:02<00:00, 1517.72it/s]
train: New cache created: /content/coco_yolo_dataset/labels/train.cache
val: Scanning /content/coco_yolo_dataset/labels/val... 400 images, 0 backgrounds, 0 corrupt: 100% 400/400 [00:00<00:00, 861.90it/s]
val: New cache created: /content/coco_yolo_dataset/labels/val.cache

AutoAnchor: 4.48 anchors/target, 0.995 Best Possible Recall (BPR). Current anchors are a good fit to dataset ✅
Plotting labels to runs_train/coco_yolov5s_run/labels.jpg...
/content/yolov5/train.py:358: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=amp)
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs_train/coco_yolov5s_run
Starting training for 30 epochs...

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       0/29      3.57G    0.06496    0.08366    0.05286        295        640: 100% 200/200 [01:28<00:00,  2.27it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:09<00:00,  1.31it/s]
                   all        400       3846      0.379     0.0444     0.0179    0.00637

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       1/29      4.47G    0.07272    0.08595    0.06486        224        640: 100% 200/200 [01:24<00:00,  2.36it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:09<00:00,  1.33it/s]
                   all        400       3846      0.529     0.0515     0.0242    0.00847

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       2/29      4.47G    0.07265    0.08611     0.0652        331        640: 100% 200/200 [01:22<00:00,  2.41it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:08<00:00,  1.57it/s]
                   all        400       3846      0.429     0.0709     0.0301      0.012

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       3/29      4.82G    0.07143    0.08462    0.06347        264        640: 100% 200/200 [01:21<00:00,  2.45it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:08<00:00,  1.55it/s]
                   all        400       3846      0.333      0.076      0.041     0.0139

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       4/29      4.82G    0.06929     0.0865    0.05989        196        640: 100% 200/200 [01:21<00:00,  2.45it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:07<00:00,  1.79it/s]
                   all        400       3846      0.406     0.0821     0.0621     0.0267

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       5/29      4.82G    0.06823    0.08598    0.05771        271        640: 100% 200/200 [01:19<00:00,  2.53it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:07<00:00,  1.70it/s]
                   all        400       3846      0.293      0.138     0.0802      0.032

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       6/29      4.82G    0.06631    0.08631    0.05586        206        640: 100% 200/200 [01:18<00:00,  2.54it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:07<00:00,  1.64it/s]
                   all        400       3846      0.343      0.146     0.0954      0.042

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       7/29      4.82G    0.06536    0.08535     0.0536        281        640: 100% 200/200 [01:21<00:00,  2.44it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  2.02it/s]
                   all        400       3846      0.381      0.155      0.113     0.0504

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       8/29      4.82G    0.06458    0.08442    0.05211        258        640: 100% 200/200 [01:20<00:00,  2.48it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  1.96it/s]
                   all        400       3846      0.353      0.149      0.105     0.0473

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       9/29      4.82G    0.06351    0.08417    0.05047        212        640: 100% 200/200 [01:20<00:00,  2.50it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  2.14it/s]
                   all        400       3846      0.357      0.185      0.144     0.0678

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      10/29      4.82G    0.06281     0.0836    0.04948        204        640: 100% 200/200 [01:19<00:00,  2.51it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  2.04it/s]
                   all        400       3846      0.312      0.175      0.139     0.0678

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      11/29      4.82G    0.06208     0.0838    0.04832        246        640: 100% 200/200 [01:19<00:00,  2.51it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  2.07it/s]
                   all        400       3846      0.284       0.21      0.146     0.0638

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      12/29      4.82G    0.06132    0.08179    0.04682        172        640: 100% 200/200 [01:19<00:00,  2.53it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  2.13it/s]
                   all        400       3846      0.293      0.202      0.165     0.0806

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      13/29      4.82G     0.0605    0.08126    0.04562        178        640: 100% 200/200 [01:20<00:00,  2.47it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:05<00:00,  2.22it/s]
                   all        400       3846        0.3      0.204      0.164     0.0771

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      14/29      4.82G    0.06019     0.0809    0.04469        200        640: 100% 200/200 [01:18<00:00,  2.54it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  1.88it/s]
                   all        400       3846      0.366      0.187       0.17     0.0815

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      15/29      4.82G    0.05924    0.08023    0.04298        324        640: 100% 200/200 [01:21<00:00,  2.45it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  2.10it/s]
                   all        400       3846      0.277      0.243      0.202      0.103

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      16/29      4.82G    0.05874    0.08012    0.04204        255        640: 100% 200/200 [01:22<00:00,  2.44it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:05<00:00,  2.17it/s]
                   all        400       3846      0.363      0.239      0.203        0.1

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      17/29      4.82G    0.05816     0.0802    0.04152        191        640: 100% 200/200 [01:21<00:00,  2.46it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  2.11it/s]
                   all        400       3846      0.345      0.255      0.213      0.109

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      18/29      4.82G    0.05735    0.07867    0.03972        257        640: 100% 200/200 [01:18<00:00,  2.55it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  2.12it/s]
                   all        400       3846      0.387       0.24      0.217      0.115

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      19/29      4.82G    0.05689    0.07839    0.03898        283        640: 100% 200/200 [01:19<00:00,  2.51it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  2.10it/s]
                   all        400       3846       0.34      0.258      0.226      0.116

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      20/29      4.82G    0.05588    0.07661    0.03796        235        640: 100% 200/200 [01:19<00:00,  2.51it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  1.96it/s]
                   all        400       3846      0.324      0.272      0.235      0.127

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      21/29      4.82G    0.05537    0.07809    0.03647        151        640: 100% 200/200 [01:19<00:00,  2.53it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  1.95it/s]
                   all        400       3846      0.336      0.261      0.239      0.129

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      22/29      4.82G    0.05482    0.07711    0.03592        205        640: 100% 200/200 [01:19<00:00,  2.50it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:07<00:00,  1.86it/s]
                   all        400       3846      0.354      0.276       0.26      0.135

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      23/29      4.82G    0.05386    0.07593    0.03451        233        640: 100% 200/200 [01:19<00:00,  2.51it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  1.89it/s]
                   all        400       3846       0.41      0.266       0.26      0.143

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      24/29      4.82G    0.05385    0.07617    0.03412        239        640: 100% 200/200 [01:16<00:00,  2.60it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  2.04it/s]
                   all        400       3846      0.356      0.292      0.266      0.147

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      25/29      4.82G    0.05275    0.07467    0.03324        193        640: 100% 200/200 [01:19<00:00,  2.50it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  1.94it/s]
                   all        400       3846      0.394      0.273      0.269      0.148

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      26/29      4.82G    0.05255    0.07525    0.03272        230        640: 100% 200/200 [01:19<00:00,  2.50it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  1.89it/s]
                   all        400       3846      0.366      0.296      0.281      0.157

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      27/29      4.82G    0.05205    0.07359    0.03206        190        640: 100% 200/200 [01:18<00:00,  2.56it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  1.90it/s]
                   all        400       3846      0.406      0.289      0.287      0.164

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      28/29      4.82G    0.05172    0.07364    0.03155        229        640: 100% 200/200 [01:17<00:00,  2.58it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:06<00:00,  2.14it/s]
                   all        400       3846      0.387      0.288      0.287       0.16

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      29/29      4.82G    0.05172    0.07355    0.03101        234        640: 100% 200/200 [01:18<00:00,  2.55it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:05<00:00,  2.20it/s]
                   all        400       3846      0.383      0.291      0.289      0.165

30 epochs completed in 0.735 hours.
Optimizer stripped from runs_train/coco_yolov5s_run/weights/last.pt, 14.9MB
Optimizer stripped from runs_train/coco_yolov5s_run/weights/best.pt, 14.9MB

Validating runs_train/coco_yolov5s_run/weights/best.pt...
Fusing layers...
Model summary: 157 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:08<00:00,  1.57it/s]
                   all        400       3846      0.384       0.29      0.289      0.166
                person        400       1003      0.587      0.573      0.571      0.307
               bicycle        400         23      0.376      0.435       0.41      0.177
                   car        400        163       0.48      0.441      0.411      0.204
            motorcycle        400         36      0.547       0.25      0.258      0.125
              airplane        400         17      0.196      0.173      0.126     0.0741
                   bus        400         17      0.536      0.475      0.431      0.262
                 train        400         10       0.21        0.2       0.22     0.0962
                 truck        400         31      0.285      0.226       0.21      0.115
                  boat        400         69      0.254      0.143      0.106     0.0369
         traffic light        400         33      0.391      0.303      0.311      0.144
          fire hydrant        400         14      0.576      0.429      0.497      0.331
             stop sign        400          3      0.254      0.667      0.666      0.567
         parking meter        400         13      0.422      0.308      0.376      0.246

In [16]:
# 3.3 Convert our own val split to a COCO-format ground-truth JSON, using the COCO API's expected schema
import json

def yolo_to_coco_gt(images_dir, labels_dir, class_names, out_path):
    images, annotations = [], []
    ann_id = 1
    for img_name in sorted(os.listdir(images_dir)):
        stem = os.path.splitext(img_name)[0]
        img_id = int(stem)
        img_path = os.path.join(images_dir, img_name)
        h, w = cv2.imread(img_path).shape[:2]
        images.append({"id": img_id, "file_name": img_name, "height": h, "width": w})

        lbl_path = os.path.join(labels_dir, stem + ".txt")
        if not os.path.exists(lbl_path):
            continue
        with open(lbl_path) as f:
            for line in f.read().strip().splitlines():
                if not line:
                    continue
                cls, xc, yc, bw, bh = map(float, line.split())
                box_w, box_h = bw * w, bh * h
                x = xc * w - box_w / 2
                y = yc * h - box_h / 2
                annotations.append({
                    "id": ann_id, "image_id": img_id, "category_id": int(cls),
                    "bbox": [x, y, box_w, box_h], "area": box_w * box_h, "iscrowd": 0,
                })
                ann_id += 1

    cats = [{"id": i, "name": n} for i, n in enumerate(class_names)]
    with open(out_path, "w") as f:
        json.dump({"images": images, "annotations": annotations, "categories": cats}, f)

yolo_to_coco_gt(
    images_dir=os.path.join(FINAL_DIR, "images", "val"),
    labels_dir=os.path.join(FINAL_DIR, "labels", "val"),
    class_names=COCO_CLASSES,
    out_path="coco_val_gt.json",
)
print("Ground-truth COCO-format val annotations written to coco_val_gt.json")

Ground-truth COCO-format val annotations written to coco_val_gt.json

In [17]:
# 3.4 Run YOLOv5's val.py for EACH trained variant (produces predictions.json per variant)
for variant in YOLO_VARIANTS:
    best_weights = f"runs_train/coco_{variant}_run/weights/best.pt"

    if not os.path.exists(best_weights):
        print(f"\n===== Skipping evaluation for {variant}: {best_weights} not found "
              f"(training did not complete for this variant) =====")
        continue

    print(f"\n===== Evaluating {variant} =====")
    !python yolov5/val.py \
        --img {IMG_SIZE} \
        --data coco_subset.yaml \
        --weights {best_weights} \
        --task val \
        --save-json \
        --project runs_val \
        --name coco_{variant}_val \
        --exist-ok

===== Evaluating yolov5s =====
val: data=coco_subset.yaml, weights=['runs_train/coco_yolov5s_run/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, max_det=300, task=val, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=True, project=runs_val, name=coco_yolov5s_val, exist_ok=True, half=False, dnn=False
YOLOv5 🚀 v7.0-519-g6be609f3 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 157 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
val: Scanning /content/coco_yolo_dataset/labels/val.cache... 400 images, 0 backgrounds, 0 corrupt: 100% 400/400 [00:00<?, ?it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:10<00:00,  1.18it/s]
                   all        400       3846      0.383       0.29      0.289      0.165
Speed: 0.3ms pre-process, 8.4ms inference, 4.4ms NMS per image at shape (32, 3, 640, 640)

Evaluating pycocotools mAP... saving runs_val/coco_yolov5s_val/best_predictions.json...
loading annotations into memory...
pycocotools unable to run: [Errno 2] No such file or directory: '/content/coco_yolo_dataset/annotations/instances_val2017.json'
Results saved to runs_val/coco_yolov5s_val

===== Evaluating yolov5m =====
val: data=coco_subset.yaml, weights=['runs_train/coco_yolov5m_run/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, max_det=300, task=val, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=True, project=runs_val, name=coco_yolov5m_val, exist_ok=True, half=False, dnn=False
YOLOv5 🚀 v7.0-519-g6be609f3 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 212 layers, 21172173 parameters, 0 gradients, 48.9 GFLOPs
val: Scanning /content/coco_yolo_dataset/labels/val.cache... 400 images, 0 backgrounds, 0 corrupt: 100% 400/400 [00:00<?, ?it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:14<00:00,  1.09s/it]
                   all        400       3846       0.38      0.311      0.297      0.179
Speed: 0.3ms pre-process, 20.2ms inference, 3.1ms NMS per image at shape (32, 3, 640, 640)

Evaluating pycocotools mAP... saving runs_val/coco_yolov5m_val/best_predictions.json...
loading annotations into memory...
pycocotools unable to run: [Errno 2] No such file or directory: '/content/coco_yolo_dataset/annotations/instances_val2017.json'
Results saved to runs_val/coco_yolov5m_val

===== Evaluating yolov5l =====
val: data=coco_subset.yaml, weights=['runs_train/coco_yolov5l_run/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, max_det=300, task=val, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=True, project=runs_val, name=coco_yolov5l_val, exist_ok=True, half=False, dnn=False
YOLOv5 🚀 v7.0-519-g6be609f3 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 267 layers, 46533693 parameters, 0 gradients, 109.0 GFLOPs
val: Scanning /content/coco_yolo_dataset/labels/val.cache... 400 images, 0 backgrounds, 0 corrupt: 100% 400/400 [00:00<?, ?it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 13/13 [00:21<00:00,  1.65s/it]
                   all        400       3846       0.44      0.295      0.302      0.183
Speed: 0.3ms pre-process, 36.7ms inference, 2.7ms NMS per image at shape (32, 3, 640, 640)

Evaluating pycocotools mAP... saving runs_val/coco_yolov5l_val/best_predictions.json...
loading annotations into memory...
pycocotools unable to run: [Errno 2] No such file or directory: '/content/coco_yolo_dataset/annotations/instances_val2017.json'
Results saved to runs_val/coco_yolov5l_val

In [18]:
# 3.5 Score every variant's predictions with the COCO API (COCOeval) mAP, AP50, AP75
from pycocotools.coco import COCO as COCOgt
from pycocotools.cocoeval import COCOeval
import glob
# COCO API: load our ground truth
coco_gt = COCOgt("coco_val_gt.json")

results_table = []
for variant in YOLO_VARIANTS:
    best_weights = f"runs_train/coco_{variant}_run/weights/best.pt"
    val_dir = f"runs_val/coco_{variant}_val"

    if not os.path.exists(best_weights):
        print(f"[SKIP] {variant}: no trained weights found at {best_weights} "
              f"-- training did not complete for this variant.")
        continue

    matches = glob.glob(f"{val_dir}/*predictions.json")
    if not matches:
        print(f"[SKIP] {variant}: no predictions.json found in {val_dir} "
              f"-- val.py did not produce output for this variant.")
        continue

    pred_json = matches[0]
    coco_dt = coco_gt.loadRes(pred_json)                    # COCO API call
    coco_eval = COCOeval(coco_gt, coco_dt, iouType="bbox")  # COCO API evaluator
    coco_eval.evaluate()
    coco_eval.accumulate()
    coco_eval.summarize()

    mAP_50_95 = coco_eval.stats[0]   # mAP @ IoU 0.50:0.95
    AP50      = coco_eval.stats[1]   # AP  @ IoU 0.50
    AP75      = coco_eval.stats[2]   # AP  @ IoU 0.75

    results_table.append({
        "variant": variant,
        "params_M": round(variant_params[variant] / 1e6, 2),
        "mAP_0.5:0.95": round(mAP_50_95, 4),
        "AP50": round(AP50, 4),
        "AP75": round(AP75, 4),
    })

import pandas as pd

if not results_table:
    raise RuntimeError(
        "No variant produced usable results -- see the [SKIP] messages above to find the root cause "
        "(most commonly: training didn't finish, e.g. due to no GPU, a Colab disconnect, or an OOM error)."
    )

accuracy_df = pd.DataFrame(results_table)
print("\n=== Accuracy comparison across YOLOv5 variants (Deliverable 3 / Criterion 1) ===")
accuracy_df

loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Loading and preparing results...
DONE (t=2.45s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=6.64s).
Accumulating evaluation results...
DONE (t=1.63s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.165
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.288
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.166
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.083
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.156
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.239
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.197
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.354
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.394
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.198
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.403
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.493
Loading and preparing results...
DONE (t=0.35s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=6.88s).
Accumulating evaluation results...
DONE (t=1.69s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.179
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.296
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.191
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.091
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.161
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.253
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.210
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.372
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.415
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.235
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.407
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.518
Loading and preparing results...
DONE (t=2.51s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=5.58s).
Accumulating evaluation results...
DONE (t=2.68s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.183
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.302
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.198
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.104
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.176
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.253
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.204
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.369
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.412
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.229
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.402
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.514

=== Accuracy comparison across YOLOv5 variants (Deliverable 3 / Criterion 1) ===

   variant  params_M  mAP_0.5:0.95    AP50    AP75
0  yolov5s      7.23        0.1645  0.2883  0.1658
1  yolov5m     21.17        0.1785  0.2964  0.1907
2  yolov5l     46.53        0.1830  0.3017  0.1977

In [19]:
# 3.6 Visualize training curves (loss, mAP over epochs) for each variant
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))

for variant in YOLO_VARIANTS:
    df = pd.read_csv(f"runs_train/coco_{variant}_run/results.csv")
    df.columns = [c.strip() for c in df.columns]
    axes[0].plot(df["epoch"], df["val/box_loss"], label=f"{variant} val box (CIoU) loss")
    axes[1].plot(df["epoch"], df["metrics/mAP_0.5"], label=f"{variant} mAP@0.5")

axes[0].set_xlabel("Epoch"); axes[0].set_ylabel("CIoU Box Loss"); axes[0].legend(); axes[0].set_title("Validation Box Loss")
axes[1].set_xlabel("Epoch"); axes[1].set_ylabel("mAP@0.5"); axes[1].legend(); axes[1].set_title("Validation mAP@0.5")
plt.tight_layout()
plt.show()

In [20]:
# 3.7 Pick the best variant (by mAP@0.5:0.95) to carry forward into deployment sections
best_row = accuracy_df.sort_values("mAP_0.5:0.95", ascending=False).iloc[0]
VARIANT = best_row["variant"]
BEST_WEIGHTS = f"runs_train/coco_{VARIANT}_run/weights/best.pt"

print(f"Best-performing variant: {VARIANT}  (mAP@0.5:0.95 = {best_row['mAP_0.5:0.95']})")
print(f"Carrying forward weights: {BEST_WEIGHTS}")

Best-performing variant: yolov5l  (mAP@0.5:0.95 = 0.183)
Carrying forward weights: runs_train/coco_yolov5l_run/weights/best.pt

## 4. Real-Time Object Detection System
### Requirement 4: OpenCV + PyTorch inference on live video / video files / images
### Criterion 2: Speed (inference time, FPS)

In [22]:
# 4.1 Load the best fine-tuned model for inference
import torch, cv2, time

detector = torch.hub.load("ultralytics/yolov5", "custom", path=BEST_WEIGHTS, force_reload=False)
detector.conf = 0.35   # confidence threshold
detector.iou  = 0.45   # NMS IoU threshold

device = "cuda" if torch.cuda.is_available() else "cpu"
detector.to(device)
print(f"Detector ({VARIANT}) loaded on: {device}")

Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2026-7-21 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 267 layers, 46533693 parameters, 0 gradients, 109.0 GFLOPs
Adding AutoShape...

Detector (yolov5l) loaded on: cuda

In [23]:
# 4.2 Single-image inference
def detect_image(image_path, save_path="detection_output.jpg"):
    frame = cv2.imread(image_path)
    results = detector(frame[:, :, ::-1])         # BGR -> RGB
    annotated = results.render()[0][:, :, ::-1]   # RGB -> BGR for OpenCV/imwrite
    cv2.imwrite(save_path, annotated)
    print(f"Saved annotated detection to {save_path}")
    return annotated

# Example (pick a real image from the held-out test split):
test_dir = os.path.join(FINAL_DIR, "images", "test")
if os.listdir(test_dir):
    sample_img = os.path.join(test_dir, os.listdir(test_dir)[0])
    detect_image(sample_img)

Saved annotated detection to detection_output.jpg

In [32]:
# Then point detect_video() at your file, e.g.:
detect_video("/persons.mp4", save_path="detection_output.mp4")

Processed video saved to detection_output.mp4. Average inference FPS: 37.14

37.14253691894738

In [35]:
# 4.3 Video-file inference with per-frame timing
def detect_video(video_path, save_path="detection_output.mp4"):
    cap = cv2.VideoCapture(video_path)
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    fps_in = cap.get(cv2.CAP_PROP_FPS) or 25
    w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    writer = cv2.VideoWriter(save_path, fourcc, fps_in, (w, h))

    frame_times = []
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        t0 = time.time()
        results = detector(frame[:, :, ::-1])
        annotated = results.render()[0][:, :, ::-1]
        frame_times.append(time.time() - t0)
        writer.write(annotated)

    cap.release()
    writer.release()
    avg_fps = 1.0 / (sum(frame_times) / len(frame_times)) if frame_times else 0
    print(f"Processed video saved to {save_path}. Average inference FPS: {avg_fps:.2f}")
    return avg_fps

In [25]:
# 4.4 Benchmark inference SPEED across all three trained variants (Criterion 2: Speed)
speed_rows = []
n_warmup, n_timed = 5, 30
test_images = [os.path.join(test_dir, f) for f in os.listdir(test_dir)[:n_timed]]

for variant in YOLO_VARIANTS:
    weights_path = f"runs_train/coco_{variant}_run/weights/best.pt"
    m = torch.hub.load("ultralytics/yolov5", "custom", path=weights_path, force_reload=False)
    m.to(device)

    for img_path in test_images[:n_warmup]:
        frame = cv2.imread(img_path)
        _ = m(frame[:, :, ::-1])

    times = []
    for img_path in test_images:
        frame = cv2.imread(img_path)
        t0 = time.time()
        _ = m(frame[:, :, ::-1])
        times.append(time.time() - t0)

    avg_ms = (sum(times) / len(times)) * 1000
    fps = 1000 / avg_ms
    speed_rows.append({"variant": variant, "avg_inference_ms": round(avg_ms, 2), "fps": round(fps, 2)})
    del m

speed_df = pd.DataFrame(speed_rows)
print("\n=== Speed comparison across YOLOv5 variants (Criterion 2) ===")
speed_df

Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2026-7-21 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 157 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Adding AutoShape...
Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2026-7-21 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 212 layers, 21172173 parameters, 0 gradients, 48.9 GFLOPs
Adding AutoShape...
Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2026-7-21 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 267 layers, 46533693 parameters, 0 gradients, 109.0 GFLOPs
Adding AutoShape...

=== Speed comparison across YOLOv5 variants (Criterion 2) ===

   variant  avg_inference_ms    fps
0  yolov5s             21.07  47.46
1  yolov5m             23.54  42.48
2  yolov5l             38.39  26.05

## 5. Model Deployment
### Requirement 5: Deploy on edge devices (Jetson/RPi), optimize with quantization + pruning

In [26]:
# 5.1 Export best-variant weights to ONNX and TorchScript for edge deployment
!python yolov5/export.py \
    --weights {BEST_WEIGHTS} \
    --img {IMG_SIZE} \
    --include onnx torchscript \
    --simplify

export: data=yolov5/data/coco128.yaml, weights=['runs_train/coco_yolov5l_run/weights/best.pt'], imgsz=[640], batch_size=1, device=cpu, half=False, inplace=False, keras=False, optimize=False, int8=False, per_tensor=False, dynamic=False, cache=, simplify=True, mlmodel=False, opset=17, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['onnx', 'torchscript']
YOLOv5 🚀 v7.0-519-g6be609f3 Python-3.12.13 torch-2.11.0+cu128 CPU

Fusing layers...
Model summary: 267 layers, 46533693 parameters, 0 gradients, 109.0 GFLOPs

PyTorch: starting from runs_train/coco_yolov5l_run/weights/best.pt with output shape (1, 25200, 85) (89.4 MB)

TorchScript: starting export with torch 2.11.0+cu128...
TorchScript: export success ✅ 14.4s, saved as runs_train/coco_yolov5l_run/weights/best.torchscript (178.2 MB)
requirements: Ultralytics requirement ['onnxscript'] not found, attempting AutoUpdate...
Using Python 3.12.13 environment at: /usr
Resolved 10 packages in 241ms
Prepared 2 packages in 55ms
Installed 2 packages in 5ms
 + onnx-ir==0.2.1
 + onnxscript==0.7.1

requirements: AutoUpdate success ✅ 0.8s
WARNING ⚠️ requirements: Restart runtime or rerun command for updates to take effect


ONNX: starting export with onnx 1.22.0...
W0721 18:03:28.707000 84972 torch/onnx/_internal/exporter/_compat.py:133] Setting ONNX exporter to use operator set version 18 because the requested opset_version 17 is a lower version than we have implementations for. Automatic version conversion will be performed, which may not be successful at converting to the requested version. If version conversion is unsuccessful, the opset version of the exported model will be kept at 18. Please consider setting opset_version >=18 to leverage latest ONNX features
/usr/lib/python3.12/copyreg.py:99: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  return cls.__new__(cls, *args)
The model version conversion is not supported by the onnxscript version converter and fallback is enabled. The model will be converted using the onnx C API (target version: 17).
Failed to convert the model to the target version 17 using the ONNX C API. The model was not modified
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/onnxscript/version_converter/__init__.py", line 137, in call
    converted_proto = _c_api_utils.call_onnx_api(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/onnxscript/version_converter/_c_api_utils.py", line 65, in call_onnx_api
    result = func(proto)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/onnxscript/version_converter/__init__.py", line 132, in _partial_convert_version
    return onnx.version_converter.convert_version(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/onnx/version_converter.py", line 39, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: /project/onnx/version_converter/BaseConverter.h:64: adapter_lookup: Assertion `false` failed: No Adapter To Version $17 for Resize
requirements: Ultralytics requirement ['onnxslim'] not found, attempting AutoUpdate...
Using Python 3.12.13 environment at: /usr
Resolved 10 packages in 366ms
Prepared 2 packages in 31ms
Installed 2 packages in 6ms
 + colorama==0.4.6
 + onnxslim==0.1.94

requirements: AutoUpdate success ✅ 0.5s
WARNING ⚠️ requirements: Restart runtime or rerun command for updates to take effect

ONNX: slimming with onnxslim 0.1.94...
ONNX: export success ✅ 20.5s, saved as runs_train/coco_yolov5l_run/weights/best.onnx (178.0 MB)

Export complete (38.5s)
Results saved to /content/runs_train/coco_yolov5l_run/weights
Detect:          python detect.py --weights runs_train/coco_yolov5l_run/weights/best.onnx
Validate:        python val.py --weights runs_train/coco_yolov5l_run/weights/best.onnx
PyTorch Hub:     model = torch.hub.load('ultralytics/yolov5', 'custom', 'runs_train/coco_yolov5l_run/weights/best.onnx')
Visualize:       https://netron.app

In [27]:
# 5.2 Dynamic quantization (INT8 weights) for faster CPU inference, e.g. Raspberry Pi
import torch.nn as nn

fp32_model = torch.hub.load("ultralytics/yolov5", "custom", path=BEST_WEIGHTS, force_reload=False)
fp32_model.eval()

quantized_model = torch.quantization.quantize_dynamic(
    fp32_model.model,
    {nn.Linear, nn.Conv2d},
    dtype=torch.qint8,
)
torch.save(quantized_model.state_dict(), "yolov5_quantized.pt")

orig_size  = os.path.getsize(BEST_WEIGHTS) / 1e6
quant_size = os.path.getsize("yolov5_quantized.pt") / 1e6
print(f"Original weights size : {orig_size:.2f} MB")
print(f"Quantized weights size: {quant_size:.2f} MB")

Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2026-7-21 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 267 layers, 46533693 parameters, 0 gradients, 109.0 GFLOPs
Adding AutoShape...
/tmp/ipykernel_680/4112004806.py:7: DeprecationWarning: torch.ao.quantization is deprecated and will be removed in 2.10.
For migrations of users:
1. Eager mode quantization (torch.ao.quantization.quantize, torch.ao.quantization.quantize_dynamic), please migrate to use torchao eager mode quantize_ API instead
2. FX graph mode quantization (torch.ao.quantization.quantize_fx.prepare_fx,torch.ao.quantization.quantize_fx.convert_fx, please migrate to use torchao pt2e quantization API instead (prepare_pt2e, convert_pt2e)
3. pt2e quantization has been migrated to torchao (https://github.com/pytorch/ao/tree/main/torchao/quantization/pt2e)
see https://github.com/pytorch/ao/issues/2259 for more details
  quantized_model = torch.quantization.quantize_dynamic(

Original weights size : 93.70 MB
Quantized weights size: 186.22 MB

In [28]:
# 5.3 Magnitude pruning: zero out the smallest-magnitude conv weights
import torch.nn.utils.prune as prune

prune_model = torch.hub.load("ultralytics/yolov5", "custom", path=BEST_WEIGHTS, force_reload=False)
prune_model.eval()

PRUNE_AMOUNT = 0.30  # remove 30% of weights per conv layer, ranked by L1 magnitude

for module in prune_model.model.modules():
    if isinstance(module, nn.Conv2d):
        prune.l1_unstructured(module, name="weight", amount=PRUNE_AMOUNT)
        prune.remove(module, "weight")

torch.save(prune_model.model.state_dict(), "yolov5_pruned.pt")
print(f"Pruned {PRUNE_AMOUNT:.0%} of conv weights (L1 magnitude) and saved to yolov5_pruned.pt")

Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2026-7-21 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 267 layers, 46533693 parameters, 0 gradients, 109.0 GFLOPs
Adding AutoShape...

Pruned 30% of conv weights (L1 magnitude) and saved to yolov5_pruned.pt

## 6. Robustness Testing
### Criterion 3: Robustness to lighting conditions, occlusions, and object variations

We synthetically perturb a held-out sample of test images in three controlled ways and
re-run detection, comparing detection **count** and **average confidence** against the
unperturbed originals. This directly measures how much performance degrades under each
condition, which is what "robustness" means in the evaluation criteria.

In [29]:
# 6.1 Define the three perturbation types
def apply_lighting_change(image, factor):
    """factor > 1 brightens, factor < 1 darkens (simulates different lighting conditions)."""
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV).astype(np.float32)
    hsv[:, :, 2] = np.clip(hsv[:, :, 2] * factor, 0, 255)
    return cv2.cvtColor(hsv.astype(np.uint8), cv2.COLOR_HSV2BGR)

def apply_occlusion(image, patch_fraction=0.25):
    """Blacks out a random square patch to simulate a partially occluded object."""
    out = image.copy()
    h, w = out.shape[:2]
    patch_h, patch_w = int(h * patch_fraction), int(w * patch_fraction)
    y0 = random.randint(0, h - patch_h)
    x0 = random.randint(0, w - patch_w)
    out[y0:y0 + patch_h, x0:x0 + patch_w] = 0
    return out

def apply_scale_variation(image, scale_factor):
    """Shrinks the image then pads back to original size (simulates smaller/farther objects)."""
    h, w = image.shape[:2]
    new_h, new_w = int(h * scale_factor), int(w * scale_factor)
    small = cv2.resize(image, (new_w, new_h))
    canvas = np.zeros_like(image)
    top, left = (h - new_h) // 2, (w - new_w) // 2
    canvas[top:top + new_h, left:left + new_w] = small
    return canvas

print("Perturbation functions ready: lighting, occlusion, scale variation.")

Perturbation functions ready: lighting, occlusion, scale variation.

In [30]:
# 6.2 Run the robustness benchmark: baseline vs. each perturbation
ROBUSTNESS_SAMPLE = [os.path.join(test_dir, f) for f in os.listdir(test_dir)[:40]]

def score_condition(image_list, transform_fn=None):
    """Runs detection over a list of images and returns (avg_num_detections, avg_confidence)."""
    detection_counts, confidences = [], []
    for img_path in image_list:
        frame = cv2.imread(img_path)
        if frame is None:
            continue
        if transform_fn is not None:
            frame = transform_fn(frame)
        results = detector(frame[:, :, ::-1])
        preds = results.xyxy[0]  # tensor: [x1, y1, x2, y2, conf, cls]
        detection_counts.append(len(preds))
        if len(preds) > 0:
            confidences.append(preds[:, 4].mean().item())
    avg_count = np.mean(detection_counts) if detection_counts else 0
    avg_conf = np.mean(confidences) if confidences else 0
    return avg_count, avg_conf

conditions = {
    "Baseline (no perturbation)": None,
    "Low light (0.4x brightness)": lambda im: apply_lighting_change(im, 0.4),
    "Bright light (1.8x brightness)": lambda im: apply_lighting_change(im, 1.8),
    "Occlusion (25% random patch)": lambda im: apply_occlusion(im, 0.25),
    "Scale variation (50% smaller)": lambda im: apply_scale_variation(im, 0.5),
}

robustness_rows = []
for cond_name, fn in conditions.items():
    avg_count, avg_conf = score_condition(ROBUSTNESS_SAMPLE, fn)
    robustness_rows.append({
        "condition": cond_name,
        "avg_detections_per_image": round(avg_count, 2),
        "avg_confidence": round(avg_conf, 3),
    })

robustness_df = pd.DataFrame(robustness_rows)
print("\n=== Robustness comparison (Criterion 3) ===")
robustness_df

=== Robustness comparison (Criterion 3) ===

                        condition  avg_detections_per_image  avg_confidence
0      Baseline (no perturbation)                      4.82           0.561
1     Low light (0.4x brightness)                      4.18           0.560
2  Bright light (1.8x brightness)                      4.28           0.572
3    Occlusion (25% random patch)                      4.82           0.546
4   Scale variation (50% smaller)                      3.28           0.592

In [31]:
# 6.3 Visualize robustness degradation relative to baseline
baseline_count = robustness_df.iloc[0]["avg_detections_per_image"]
robustness_df["pct_of_baseline_detections"] = (
    robustness_df["avg_detections_per_image"] / baseline_count * 100
).round(1)

fig, ax = plt.subplots(figsize=(9, 4.5))
ax.bar(robustness_df["condition"], robustness_df["pct_of_baseline_detections"], color="steelblue")
ax.axhline(100, color="gray", linestyle="--", linewidth=1)
ax.set_ylabel("Detections retained vs. baseline (%)")
ax.set_title("Robustness: detection retention under perturbation")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.show()

robustness_df

,condition,avg_detections_per_image,avg_confidence,pct_of_baseline_detections
0,Baseline (no perturbation),4.82,0.561,100.0
1,Low light (0.4x brightness),4.18,0.560,86.7
2,Bright light (1.8x brightness),4.28,0.572,88.8
3,Occlusion (25% random patch),4.82,0.546,100.0
4,Scale variation (50% smaller),3.28,0.592,68.0